import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Progress from "./components/Progress";
import Cursor from "./components/Cursor";

const mangoGrotesque = localFont({
  src: "./fonts/MangoGrotesque-Light.woff2",
  variable: "--font-mango-grotesque",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${mangoGrotesque.className} antialiased`}
      >
        <Cursor />
        <Progress />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
